// from WRL sample (adapted)

// import "inspectable.idl";
// import "Windows.Foundation.idl";
import "Windows.Media.idl";

#define COMPONENT_VERSION 1.0

namespace CaptureMediaSink
{
    //    [uuid(0A5284F4-B9B2-4450-89DF-0810206571DD)]    
    [version(COMPONENT_VERSION), activatable(COMPONENT_VERSION)]
//    runtimeclass CaptureSink
    runtimeclass CSink
    {
        [default] interface Windows.Media.IMediaExtension;
    }
}


#if 0

// adapted from MediaExtension sample

// import "inspectable.idl";
import "Windows.Media.idl";
// import "Mfidl.idl";

#include <sdkddkver.h>

namespace CaptureMediaSink
{
    runtimeclass CaptureSink;

    [exclusiveto(CaptureSink)]
    [uuid(15A600CA-9490-4F3F-8B88-065837EB92E2)]
    [version(1.0)]
    interface ICaptureSink : IInspectable
    {

    };

    [version(NTDDI_WIN8)]
    [activatable(NTDDI_WIN8)]
    runtimeclass CaptureSink
    {
        [default] interface Windows.Media.IMediaExtension;
    }
}
#endif

