// adapted from MediaExtension sample

// import "inspectable.idl";
import "Windows.Media.idl";
// import "Mfidl.idl";

#include <sdkddkver.h>

namespace CaptureMediaSink
{
    runtimeclass CaptureMediaStreamSink;

    [exclusiveto(CaptureMediaStreamSink)]
    [uuid(0A5284F4-B9B2-4450-89DF-0810206571DD)]
    [version(1.0)]
    interface ICaptureMediaStreamSink : IInspectable
    {

    };

    [version(NTDDI_WIN8)]
    // [activatable(NTDDI_WIN8)]
    runtimeclass CaptureMediaStreamSink
    {
        [default] interface ICaptureMediaStreamSink;
        // [default] interface IMFMediaSink;
        // [default] interface Windows.Media.IMFStreamSink;
    }
}


#if 0

// from WRL sample (adapted)

// import "inspectable.idl";
// import "Windows.Foundation.idl";
import "Windows.Media.idl";

#define COMPONENT_VERSION 1.0

namespace CaptureMediaSink
{
    //    [uuid(0A5284F4-B9B2-4450-89DF-0810206571DD)]    
    [version(COMPONENT_VERSION), activatable(COMPONENT_VERSION)]
    runtimeclass CaptureSink
    {
        [default] interface Windows::Media::IMediaExtension;
    }
}
#endif

