import "Windows.Media.idl";

#include <sdkddkver.h>

namespace CaptureMediaExtensionPlugin
{
	[version(NTDDI_WIN8)]
	runtimeclass CaptureMediaExtensionEffect 
        {
            interface Windows.Media.IMediaExtension;
	}
}