//
// CinderMain: a base class for Cinder Applications using XAML
//
// nb. this file was generated by the Windows 8.1 Store XAML template as DirectXPage, then modified for Cinder

// The copyright in this software is being made available under the BSD License, included below. 
// This software may be subject to other third party and contributor rights, including patent rights, 
// and no such rights are granted under this license.
//
// Copyright (c) 2013, Microsoft Open Technologies, Inc. 
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, 
// are permitted provided that the following conditions are met:
//
// - Redistributions of source code must retain the above copyright notice, 
//   this list of conditions and the following disclaimer.
// - Redistributions in binary form must reproduce the above copyright notice, 
//   this list of conditions and the following disclaimer in the documentation 
//   and/or other materials provided with the distribution.
// - Neither the name of Microsoft Open Technologies, Inc. nor the names of its contributors 
//   may be used to endorse or promote products derived from this software 
//   without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
// EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#pragma once

/*

namespaces used

CinderXAML::        all XAML content generated by Windows 8.1 Store/XAML template, then modified for Cinder
                    pages are: App.xaml, CinderPage.xaml (this was the DirectXPage from the template)

DX::                DirectX helper and DeviceResources in the Common/ folder, generated by template

cinder::app::       contains CinderMain class that the application inherits from
cinder::dx::        contains the DirectX drawing methods, see dx.h

*/


#include "cinder/Cinder.h"

#include "cinder/app/AppImplMswRendererDx.h"

#include "cinder/Vector.h"
#include "cinder/app/MouseEvent.h"
#include "cinder/app/KeyEvent.h"

using namespace Windows::UI::Core;

// fwd decls
namespace DX {
    class StepTimer;
    class DeviceResources;
    class DeviceRelay;
}

namespace cinder { namespace app {

    class CinderMain
    {
    public:
        CinderMain() : m_timer(nullptr), m_relay(nullptr) {}
        ~CinderMain();

        /* 
        // zv now called through ::app
        //
        // Cinder methods (app will inherit these)
        virtual void mouseDrag(MouseEvent event) {}
        virtual void keyDown(KeyEvent event) {}
        virtual void update() {}
        virtual void draw() {}
        virtual void setup() {}     // nb. as in Processing
        */

        // setFullScreen: n/a: a Windows RT store app is always full screen
        //
        // zv todo multitouch: TBD
        // void enableMultiTouch( bool enable = true ) { mEnableMultiTouch = enable; }
        // 
        // cursor: does not apply
        //
        // framerate: changing it is useful, not implemented now
        //
        // quit: TBD, stop the RenderLoop
        //  nb. WinRT OS kills the app when it needs to, otherwise the app always runs
        //  nb. RenderLoop is automatically paused when the app is not visible, by XAML framework


        // Methods called by XAML via CinderPage
        void setup(const std::shared_ptr<DX::DeviceResources>& deviceResources);
        void CreateWindowSizeDependentResources();

        // pointer
        void StartTracking() {  m_tracking = true; }
        void TrackingUpdate(PointerEventArgs^ e);
        void StopTracking() { m_tracking = false; }
        bool IsTracking() { return m_tracking; }

        // rendering
        void StartRenderLoop();
        void StopRenderLoop();
        Concurrency::critical_section& GetCriticalSection() { return m_criticalSection; }

        // share the DX/D3D/D2D objects with Cinder
        void shareWithCinder();

        // IDeviceNotify
        virtual void OnDeviceLost();
        virtual void OnDeviceRestored();

        // singleton
        static CinderMain*  getInstance() { return sInstance; }

        cinder::app::AppImplMswRendererDx *getRenderer() { return ren; }

    private:

        // singleton enforcement:
        CinderMain(CinderMain const &);
        void operator=(CinderMain const &);

        // owner/ptr to Cinder renderer for DirectX
        cinder::app::AppImplMswRendererDx *ren;

        bool    m_tracking;
        bool    m_pipeline_ready;

        // zv
        // singleton instance
        static CinderMain*  sInstance;

        // relay for device lost/restored events from XAML
        DX::DeviceRelay* m_relay;

        void ProcessInput();
        void Update();
        bool Render();

        // Cached pointer to device resources.
        std::shared_ptr<DX::DeviceResources> m_deviceResources;

        // optional: frame rate display
        // std::unique_ptr<SampleFpsTextRenderer> m_fpsTextRenderer;

        Windows::Foundation::IAsyncAction^ m_renderLoopWorker;
        Concurrency::critical_section m_criticalSection;

        // Rendering loop timer.
        DX::StepTimer* m_timer;
    };

} }

// eof
